# Generated by Django 2.0.6 on 2018-06-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_page_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wenzhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biaoti', models.CharField(default='', max_length=200)),
                ('zhengwen', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
